version: '3.8'

services:
  pompom-database:
    container_name: pompom-database
    env_file:
      - .env
    image: mariadb:10.9
    ports:
      - "3307:3306"
    volumes:
        - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
        - pompom-network
    restart: always
    hostname: pompom-database

  pompom-bot:
    image: pompom-bot
    container_name: pompom-bot
    depends_on:
      - pompom-database
    networks:
      - pompom-network
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    restart: always
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@pompom-database:3307/${MYSQL_DATABASE}
    hostname: pompom-bot

networks:
    pompom-network:
      external: false
      name: pompom-network